site_name: MPFS Cage Specification
site_url: https://cardano-foundation.github.io/cardano-mpfs-cage/
repo_url: https://github.com/cardano-foundation/cardano-mpfs-cage

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.path
    - toc.integrate
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - tables
  - footnotes
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - Architecture:
      - Types: architecture/types.md
      - Properties: architecture/properties.md
